from .funcionalidades import logger_id
from .funcionalidades import format_message
from .funcionalidades import log_info
from .funcionalidades import log_debug
from .funcionalidades import log_error
from .funcionalidades import log_warning
from .funcionalidades import log_critical
from .funcionalidades import init
from .funcionalidades import close
